### ISSUE TITLE
Futures 0.2 Compatibility on Crates.io and future release?

### ISSUE THREAD

**Issue by ssbanerje** [alexcrichton/futures-timer#8]
I had a couple of questions about how this crate will interface with the `futures` and `tokio` crates in the future?

* Why is the futures-0.2 compatible version of this crate not on crates.io? Something experimental here?

* Will this crate be moved into the `futures` facade crate for v0.3/v1? I see that the tokio reform [RFC](https://github.com/tokio-rs/tokio-rfcs/blob/master/text/0001-tokio-reform.md) seems to suggest 
> Similarly, decouple timer futures from Tokio, providing functionality instead through a new futures-timer crate.

**Comment by alexcrichton** [comment]
I believe futures 0.2 has now been yanked, so closing
